version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongPassword123!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - ./data:/data
    container_name: sqlserver

  migration:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - sqlserver
    volumes:
      - ./data:/data
    container_name: migration